title: Jain Basil's Blog
description: >-
  Notes on life, technology and other random topics.
author:
  name: Jain Basil Aliyas
  email: jainbasil@gmail.com
url: https://jainbasil.in
baseurl: "" # subpath of your site, e.g. /blog

# Build settings
theme: jekyll-calculus-theme

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - tags
  layouts: 
    year: archive-year
    tag: archive-tag
  permalinks:
    year: '/archives/:year/'
    tag: '/archives/tag/:name/'