title: Jain Basil's Blog
description: >-
  Notes on life, technology and other random topics.
author: Jain Basil Aliyas
email: mail@jainbasil.in
url: https://jainbasil.in
baseurl: "" # subpath of your site, e.g. /blog

# Build settings
theme: jekyll-calculus-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
show_excerpts: true
